### ISSUE TITLE
Direct animation and Parola zoning example

### ISSUE THREAD

**Issue by mrcodetastic** [petervflocke/ESP32MatrixClock#1]
Hi Peter,

Are you able to provide the source code for your example that you demonstrate here?

https://www.youtube.com/watch?v=mO98BBGWHkg

Thanks.

**Comment by petervflocke** [comment]
> Are you able to provide the source code for your example that you demonstrate here?
> https://www.youtube.com/watch?v=mO98BBGWHkg

Yes, attached!
[myParola_Zone_Display.ino.zip](https://github.com/petervflocke/ESP32MatrixClock/files/2555548/myParola_Zone_Display.ino.zip)

BUT: please refer to the discussion here: https://forum.arduino.cc/index.php?topic=171056.msg3459596#msg3459596

You have to modify the original library, which I do not recommend!
