### ISSUE TITLE
Maximum Max7219 Modules

### ISSUE THREAD

**Issue by Synology-John** [petervflocke/ESP32MatrixClock#2]
I am attempting to use your library but it seems to top out at 16 modules. I have 20 modules connected
The arduino is powered from the display, not the other way round 

Displays set to 5 I get 4 x 5 modules working
Displays set to 10 I get 2 x 10 modules working
Displays set to 15 I get 1 x 15 + 1 x 5 modules working
Displays set to 16 I get 1 x 16 + 1 x 4 modules working
Displays set to 17 I get 1 x 16 + 1 x blank + 3 x modules working
Displays  set to 20 I get 1 x 16 modules working + 4 x blank.
This is testing with the simple Ticker script.
Is this to do with your library or the Adafruit_GFX library
I am only just learning arduino so not very experienced.
Any help would be appreciated
Thanks

**Comment by petervflocke** [comment]
Sorry for long delay. The clock works and I did not check my "developer corner" for a long time.
I did not get you. What does it mean "Displays set to 5 I get 4 x 5 modules working"?
You have to set up an array of displays. 4x5 = 20 displays not 5
```
int numberOfHorizontalDisplays = 4;
int numberOfVerticalDisplays = 5;
```
Furthermore I would assume that if there is a problem it is related to my library not to GFX. The latter is well tested :)

What arduino board do you use?
Are you sure the electrical connection are fine?
Enough current to supply, etc. ..

I tested this with ESP32 - a lot of memory, in case of small atmel microcontrollers there might be a memory issue.

**Comment by Synology-John** [comment]
Hi Peter

Thanks for getting back to me.

The problem has been resolved.

The problem was the maximum number of modules the max7219panel  library would support.

Originally the library would only support 16 modules

After the library was edited (line 106) changed from int8_t to int16_t

It now works with more than 16 modules without error

John

**Comment by Synology-John** [comment]
Hi Peter

Just looking at your  code in the library ppmax7219panel.cpp

 

Line 124 is int8_t x = xx; this would limit the maximum number of modules in one row to 16

If it is changed to int16_t x=xx; this removes this limit

 

John

**Comment by petervflocke** [comment]
> The problem has been resolved.

Perfect! Good Job!
Best Regards
